# Generated by Django 4.2.3 on 2023-07-27 20:38

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('owner', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('vendor', models.CharField(max_length=4, validators=[users.models.validation_vendor])),
                ('bank', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
