# Generated by Django 4.2.3 on 2023-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='vendor',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MC', 'MASTER CARD'), ('MIR', 'MIR')], max_length=4),
        ),
    ]
