# Generated by Django 4.2.3 on 2023-07-28 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_creditcard_expires_at_alter_creditcard_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='vendor',
            field=models.CharField(max_length=4),
        ),
    ]
