# Generated by Django 4.2.3 on 2023-07-30 20:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_creditcard_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_uuid',
            field=models.UUIDField(default='c9af947d-af8f-473d-beda-d04e05719203'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='bank',
            field=models.CharField(choices=[('Sber', 'Sber'), ('Tinkoff', 'Tinkoff'), ('Kaspi', 'Kaspi'), ('Gazprom', 'Gazprom'), ('Unicredit', 'Unicredit')], max_length=9),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, validators=[users.models.valid_card_number]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=3, validators=[users.models.valid_cvv]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='vendor',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MIR', 'MIR'), ('MASTER CARD', 'MASTER CARD'), ('MAESTRO', 'MAESTRO')], max_length=11),
        ),
    ]
